# +----------------------------------------------------------------------
# | MCS [ MCS赋能企业，成就企业辉煌 ]
# +----------------------------------------------------------------------
# | Copyright (c) 2022~2024 https://www.mc-serve.com All rights reserved.
# +----------------------------------------------------------------------
# | Licensed MCS并不是自由软件，未经许可不能去掉MCS相关版权
# +----------------------------------------------------------------------
# | Author: MCS Team <cs@mc-serve.com>
# +----------------------------------------------------------------------
# | Standard: dev-gitlab-ci
# +----------------------------------------------------------------------

stages:          # List of stages for jobs, and their order of execution
  - install
  - test
  - build
  - deploy
  - end
  - sync

sync_to_github:
  stage: sync
  tags:
    - sync
  script:
    # 安装 SSH 客户端
    # - apt-get update -qq && apt-get install -y openssh-client
    
    # 配置专用的同步密钥
    - mkdir -p ~/.ssh
    - echo "$SYNC_GITHUB_PRIVATE_KEY" > ~/.ssh/sync_github
    - chmod 600 ~/.ssh/sync_github
    
    # 使用 GIT_SSH_COMMAND 指定使用专用密钥
    - export GIT_SSH_COMMAND='ssh -i ~/.ssh/sync_github -o StrictHostKeyChecking=no'

    # 克隆 GitHub 仓库并同步所有分支
    - if git remote | grep -q "^github$"; then echo "Remote 'github' already exists."; else git remote add github git@github.com:mc-serve/uni-app-vue3.git; fi
    - git push github --mirror
    - git fetch --all
    - git push github --all
    - git push github --tags
